# Generated by Django 5.0.4 on 2024-04-08 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='edu_email',
            field=models.CharField(blank='', default='abc@mail.com', max_length=40),
        ),
    ]
