# Generated by Django 5.0.4 on 2024-04-08 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_student_edu_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='educational_year',
            field=models.CharField(choices=[(2019, '2019'), (2020, '2020'), (2021, '2021'), (2022, '2022'), (2023, '2023')], max_length=100),
        ),
    ]
