# Generated by Django 5.0.4 on 2024-04-08 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_student_educational_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='educational_year',
            field=models.IntegerField(choices=[(2019, '2019'), (2020, '2020'), (2021, '2021'), (2022, '2022'), (2023, '2023')]),
        ),
    ]
