# Generated by Django 5.0.4 on 2024-04-08 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_student_edu_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='edu_email',
            field=models.CharField(blank=True, default='', max_length=40),
        ),
    ]
